/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new user
         * @description Create a new user.
         */
        post: operations["create_user_users_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login a user
         * @description Login a user.
         */
        post: operations["login_user_users_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/token-refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token Refresh
         * @description Return Updated JWT tokens in cookies.
         *
         *     Requires refresh token cookie.
         */
        post: operations["token_refresh_users_token_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user's info
         * @description Get current user's info.
         */
        get: operations["get_current_user_users_me_get"];
        put?: never;
        post?: never;
        /**
         * Deactivate a user's profile
         * @description Deactivate a user's profile.
         */
        delete: operations["deactivate_user_users_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all employees for current user
         * @description Get all employees for current user.
         */
        get: operations["get_all_employees_employees_get"];
        put?: never;
        /**
         * Create a new employee
         * @description Create a new employee.
         */
        post: operations["create_employee_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific employee
         * @description Get detailed info and work summary for an employee
         */
        get: operations["get_employee_detail_employees__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/work/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a new work session
         * @description Start a new work session.
         */
        post: operations["start_work_employees_work_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/work/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End a new work session
         * @description End a new work session.
         */
        post: operations["end_work_employees_work_end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/workplaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Workplace
         * @description Add a new workplace.
         */
        post: operations["add_workplace_employees_workplaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_employee_employees_post */
        Body_create_employee_employees_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Data */
            data: string;
        };
        /**
         * EmployeeReturnDetailSchema
         * @description Schema using when returning employee detail information
         */
        EmployeeReturnDetailSchema: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Position */
            position: string;
            /** Profile Photo */
            profile_photo: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone Number */
            phone_number: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            workplace: components["schemas"]["WorkPlaceReturnSchema"];
            /** Personal Token */
            personal_token: string;
        };
        /**
         * EmployeeWithStatsReturnSchema
         * @description Schema using when returning employee information with work time
         */
        EmployeeWithStatsReturnSchema: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Position */
            position: string;
            /** Profile Photo */
            profile_photo: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone Number */
            phone_number: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            workplace: components["schemas"]["WorkPlaceReturnSchema"];
            work_stats: components["schemas"]["WorkTimeStatusSchema"];
        };
        /**
         * EmployeeWorkDetailSchema
         * @description Schema using when returning employee work detail information
         */
        EmployeeWorkDetailSchema: {
            employee: components["schemas"]["EmployeeReturnDetailSchema"];
            /** Period */
            period: string;
            /** Work Summary */
            work_summary: components["schemas"]["WorkSummarySchema"][];
            /** Total Hours */
            total_hours: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * UserCreateSchema
         * @description Schema used when creating a new user.
         */
        UserCreateSchema: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password1 */
            password1: string;
            /** Password2 */
            password2: string;
        };
        /**
         * UserCurrentSchema
         * @description Schema used for current user return.
         */
        UserCurrentSchema: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserLoginSchema
         * @description Schema used when user trying to log-in
         */
        UserLoginSchema: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkPlaceReturnSchema
         * @description Schema using when returning work place
         */
        WorkPlaceReturnSchema: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Address */
            address: string;
        };
        /**
         * WorkSummarySchema
         * @description Повертає статистику за день.
         *     hours - це об'єкт time (наприклад 08:45:00) або None.
         */
        WorkSummarySchema: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Work Time */
            work_time: string | null;
        };
        /**
         * WorkTimeStatusSchema
         * @description Schema using when returning work time status
         */
        WorkTimeStatusSchema: {
            /** Today */
            today: string | null;
            /** Week */
            week: string | null;
            /** Month */
            month: string | null;
        };
        /**
         * WorkplaceCreateSchema
         * @description Schema using when creating work place
         */
        WorkplaceCreateSchema: {
            /** Title */
            title: string;
            /** Address */
            address: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_user_users_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_user_users_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_refresh_users_token_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_user_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCurrentSchema"];
                };
            };
        };
    };
    deactivate_user_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_all_employees_employees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeWithStatsReturnSchema"][];
                };
            };
        };
    };
    create_employee_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_employee_employees_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_detail_employees__employee_id__get: {
        parameters: {
            query?: {
                week?: string | null;
                month?: string | null;
            };
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeWorkDetailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_work_employees_work_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    end_work_employees_work_end_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    add_workplace_employees_workplaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkplaceCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
