"""Add personal token field to Employee model

Revision ID: 0c846a72c520
Revises: 2cf83fac527b
Create Date: 2025-11-05 15:04:59.799860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c846a72c520'
down_revision: Union[str, Sequence[str], None] = '2cf83fac527b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('personal_token', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'employees', ['personal_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'personal_token')
    # ### end Alembic commands ###
