"""Update Employee Model

Revision ID: cf4d62c9c796
Revises: 6773ca684e95
Create Date: 2025-11-18 14:20:01.632006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4d62c9c796'
down_revision: Union[str, Sequence[str], None] = '6773ca684e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('employees', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('employees', sa.Column('position', sa.String(length=50), nullable=False))
    op.add_column('employees', sa.Column('profile_photo', sa.String(length=100), nullable=True))
    op.drop_column('employees', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('employees', 'profile_photo')
    op.drop_column('employees', 'position')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    # ### end Alembic commands ###
